### ISSUE TITLE
腾讯云函数错误

### ISSUE THREAD

**Issue by 532355805** [5ime/xyb_auto_sign#2]
START RequestId:3f6f23c5-240d-43e3-8520-c5fc9d49ba0d
Stack trace:
#0 /var/runtime/php80/bootstrap.php(203): __scf_bootstrap_\EventHandler->handle(Object(stdClass), Object(stdClass))
#1 /var/runtime/php80/bootstrap.php(226): __scf_bootstrap_\__main_for_scf()
#2 {main}ERROR RequestId:3f6f23c5-240d-43e3-8520-c5fc9d49ba0d Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Exception: function main_handler not found in /var/runtime/php80/bootstrap.php:44\nStack trace:\n#0 /var/runtime/php80/bootstrap.php(203): __scf_bootstrap_\\EventHandler-\u003ehandle(Object(stdClass), Object(stdClass))\n#1 /var/runtime/php80/bootstrap.php(226): __scf_bootstrap_\\__main_for_scf()\n#2 {main}","statusCode":430}
END RequestId:3f6f23c5-240d-43e3-8520-c5fc9d49ba0d
Report RequestId:3f6f23c5-240d-43e3-8520-c5fc9d49ba0d Duration:1ms Memory:128MB MemUsage:8.064796MB

**Comment by 5ime** [comment]
emmm...云函数咋用我是没研究过，我是直接安装PHP环境使用crontab做的计划任务

**Comment by 532355805** [comment]
云函数我也装的php环境  我感觉应该大差不差吧 1 但是一运行直接报错

**Comment by 532355805** [comment]
你用的php多少版本呢

**Comment by 5ime** [comment]
> 你用的php多少版本呢

7.0-7.3 应该均可用，在往上没测过了，我是7.3

**Comment by 532355805** [comment]
好的谢谢我再研究研究
